{% set name = "docarray" %}
{% set version = "0.12.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/docarray-{{ version }}.tar.gz
  sha256: 02eb2e88e1f72d0ac8d284c6f718d08e6814cea5bb3305fa9f96a5fce26b85af

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools >=18.0
    - wheel
  run:
    - python >=3.6
    - numpy
    - rich

test:
  imports:
    - docarray
    - docarray.array
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jina-ai/docarray
  summary: The data structure for unstructured data
  dev_url: https://github.com/jina-ai/docarray/
  license: Apache-2.0
  license_file: LICENSE
  description: |
    DocArray is a library for nested, unstructured data such as text, image, 
    audio, video, 3D mesh. It allows deep learning engineers to efficiently 
    process, embed, search, recommend, store, transfer the data with Pythonic 
    API.

    🌌 **All data types**: super-expressive data structure for representing 
    complicated/mixed/nested text, image, video, audio, 3D mesh data.

    🐍 **Pythonic experience**: designed to be as easy as Python list. If 
    you know how to Python, you know how to DocArray. Intuitive idioms and 
    type annotation simplify the code you write.

    🧑‍🔬 **Data science powerhouse**: greatly accelerate data scientists work 
    on embedding, matching, visualizing, evaluating via 
    Torch/Tensorflow/ONNX/PaddlePaddle on CPU/GPU.

    🚡 **Portable**: ready-to-wire at anytime with efficient and compact 
    serialization from/to Protobuf, bytes, JSON, CSV, dataframe.

    PyPI: [https://pypi.org/project/docarray](https://pypi.org/project/docarray)

  doc_url: https://docarray.jina.ai/

extra:
  recipe-maintainers:
    - sugatoray
    # Maintainers from package (upstream) repository
    - hanxiao
    - nan-wang
    - JoanFM
